### ISSUE TITLE
would you guys mind to run vulnerability check(npm audit) and update the package?

### ISSUE THREAD

**Issue by sandyrokz4u** [doowb/group-array#13]

**Comment by konraddzbik** [comment]
Up. Our app shows that, there is a real problem with packages 
`   Package         set-value                                                    
  Patched in     >=4.0.1                                                       
  Dependency of   group-array [dev]                                             
  Path            group-array > union-value > set-value   `

**Comment by matrunchyk** [comment]
Same issue. Seems like the issue is in dependency package: https://github.com/jonschlinkert/union-value/issues/11

**Comment by doowb** [comment]
I'll look into this more over the weekend... at first glance, it looks like `union-value` just needs to be patched with a newer version of `set-value`.

**Comment by konraddzbik** [comment]
Any updates? I could make a PR, but is this repo still under maintenance?

**Comment by matrunchyk** [comment]
This is not questionable (yet) to this repository maintainer, but to the upstream one: https://github.com/jonschlinkert/union-value/pull/12

**Comment by doowb** [comment]
I published a patch to `set-value` as version `3.0.3` that back ports the fix found in `set-value@4.0.1`. Since `union-value@2.0.1` references `"set-value": "^3.0.0"`, and `group-array` references `union-value@2.0.1`, the patch should be applied when updating npm dependencies. You may have to delete `node_modules` and any `package-lock.json` files to re-install. Also, the security scanners might not be updated yet, but hopefully those will update soon.
